name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: ${{ matrix.platform }} on ${{ matrix.os }}
    runs-on: macos-15
    env:
      scheme: APProgressToolbar
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: iPhone 18 Pro
            os: 18.0
          - platform: iPhone 16 Pro
            os: 18.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Build on ${{ matrix.platform }} (iOS ${{ matrix.os }})
        run: |
          xcodebuild build \
            -scheme $scheme \
            -destination 'platform=iOS Simulator,name=${{ matrix.platform }},OS=${{ matrix.os }}'
